name: Deploy to AWS
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: "yarn"
        cache-dependency-path: infra/yarn.lock

    - run: |
        yarn install
      shell: bash
      working-directory: infra
