name: "Push to Branch"
description: "Pushes a specified commit to a deployment branch"
inputs:
  commit:
    description: "Branch/Commit ref to push"
    required: true
    default: "origin/main"
  github-token:
    description: "GitHub token for authentication"
    required: true
  branch:
    description: "Desired branch"
    required: true
    default: "staging-app"
outputs:
  deployed-commit:
    description: "The commit that was pushed to production"
    value: ${{ steps.push-to-branch.outputs.deployed-commit }}
runs:
  using: "composite"
  steps:
    - name: Push to desired branch
      id: push-to-branch
      shell: bash
      run: |
        git fetch
        git checkout -b ${{ inputs.branch }} origin/${{ inputs.branch }}
        git reset --hard ${{ inputs.commit }}
        git remote set-url origin https://${{ inputs.github-token }}@github.com/${{ github.repository }}.git
        git push origin ${{ inputs.branch }} -f
        echo "deployed-commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: Output deployment information
      shell: bash
      run: |
        echo "Pushed to ${{ inputs.branch }} branch"
        echo "Commit: ${{ steps.push-to-branch.outputs.deployed-commit }}"
